services:

  rozetkapay.module:
    class: Rozetkapay
    public: true
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'rozetkapay'

  rozetkapay.context:
    class: Context
    public: true
    factory: [ 'Context', 'getContext' ]
    
  #####################
  # PS Account
  rozetkapay.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - "5.0"

  rozetkapay.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - "@rozetkapay.ps_accounts_installer"

  #####################
  # PS Billing
  rozetkapay.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - '@rozetkapay.ps_accounts_facade'
      - '@rozetkapay.context'
      - true # if true you are in sandbox mode, if false or empty not in sandbox

  rozetkapay.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - '@rozetkapay.ps_billings_context_wrapper'
      - '@rozetkapay.module'

  # Remove this if you don't need BillingService
  rozetkapay.ps_billings_service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - '@rozetkapay.ps_billings_context_wrapper'
      - '@rozetkapay.module'